### PR TITLE
Refactored module for companion v3.0

### PR DESCRIPTION
**Pull request by tap-chris**
- Module has been updated to work with the new module api of companion v3.0
- Feedbacks have been converted to boolean type
- Renamed variables using a colon to comply with v3.0
- Added cursor control to the actions
- Added basic presets to get started

### CODE REVIEW

**Comment by josephdadams** [comment]
Package.json needs a cleanup. Too many fields left. Take a look at the wiki for upgrading 2.x to 3.x for which fields can be removed

**Comment by josephdadams** [comment]
I think the use of eval() in your feedbacks needs to be reconsidered.

**Comment by tap-chris** [comment]
> I think the use of eval() in your feedbacks needs to be reconsidered.

You're right. I've removed the evil calls.
Thanks for the help!

**Comment by josephdadams** [comment]
Overall looks great now! I’ll merge later

**Comment by tap-chris** [comment]
> Overall looks great now! I’ll merge later

Thank you and thanks again!

**Pull request merged**
